name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Запуск каждый день в полночь по UTC
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v4 # Обновленный экшен
        with:
          name: snake-artifact
          path: dist/github-contribution-grid-snake.svg
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake.svg || exit 0
          git commit -m "Update snake animation" || exit 0
          git push
